# fly.toml app configuration file generated for halo-oglasi-broken-wave-7143 on 2024-11-22T14:34:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'halo-oglasi-broken-wave-7143'
primary_region = 'lhr'

[build]


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="halo_oglasi_data"
  destination="/data"
